"""initial schema

Revision ID: e747d27c2e36
Revises: 
Create Date: 2026-07-29 14:28:20.618822

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2



# revision identifiers, used by Alembic.
revision: str = 'e747d27c2e36'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('broker', 'user', 'public', name='userrole', native_enum=False, length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_nri', sa.Boolean(), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('property_type', sa.Enum('flat', 'studio', 'villa', 'bungalow', 'duplex', 'penthouse', 'farmhouse', 'plot', 'commercial', 'office', 'shop', 'showroom', 'warehouse', 'coworking', name='propertytype', native_enum=False, length=30), nullable=False),
    sa.Column('listing_type', sa.Enum('sale', 'rent', 'lease', name='listingtype', native_enum=False, length=30), nullable=False),
    sa.Column('status', sa.Enum('active', 'sold', 'rented', 'reserved', 'under_negotiation', 'inactive', name='propertystatus', native_enum=False, length=30), nullable=True),
    sa.Column('possession_status', sa.Enum('ready_to_move', 'under_construction', name='possessionstatus', native_enum=False, length=30), nullable=True),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('price_negotiable', sa.Boolean(), nullable=True),
    sa.Column('security_deposit', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('area_sqft', sa.Float(), nullable=True),
    sa.Column('area_sqmt', sa.Float(), nullable=True),
    sa.Column('floor_number', sa.Integer(), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('age_years', sa.Integer(), nullable=True),
    sa.Column('furnished', sa.String(length=50), nullable=True),
    sa.Column('facing', sa.Enum('north', 'south', 'east', 'west', 'north_east', 'north_west', 'south_east', 'south_west', name='facing', native_enum=False, length=30), nullable=True),
    sa.Column('locality', sa.String(length=255), nullable=False),
    sa.Column('village', sa.String(length=255), nullable=True),
    sa.Column('taluka', sa.String(length=255), nullable=True),
    sa.Column('region', sa.Enum('north_goa', 'south_goa', 'central_goa', name='goaregion', native_enum=False, length=30), nullable=False),
    sa.Column('full_address', sa.Text(), nullable=True),
    sa.Column('pin_code', sa.String(length=10), nullable=True),
    sa.Column('approx_lat', sa.Float(), nullable=True),
    sa.Column('approx_lng', sa.Float(), nullable=True),
    sa.Column('exact_location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('beach_distance_km', sa.Float(), nullable=True),
    sa.Column('mopa_airport_km', sa.Float(), nullable=True),
    sa.Column('dabolim_airport_km', sa.Float(), nullable=True),
    sa.Column('tourist_density', sa.String(length=50), nullable=True),
    sa.Column('short_term_rental_potential', sa.Boolean(), nullable=True),
    sa.Column('connectivity_score', sa.Integer(), nullable=True),
    sa.Column('property_video_url', sa.String(length=500), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('nri_eligible', sa.Boolean(), nullable=True),
    sa.Column('fema_compliant', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('connectivity_score >= 1 AND connectivity_score <= 10', name='check_connectivity_score'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_index(op.f('ix_properties_locality'), 'properties', ['locality'], unique=False)
    op.create_table('enquiries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('buyer_name', sa.String(length=255), nullable=False),
    sa.Column('buyer_phone', sa.String(length=20), nullable=False),
    sa.Column('buyer_email', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_nri', sa.Boolean(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('new', 'contacted', 'site_visit', 'negotiation', 'closed', 'lost', name='leadstatus', native_enum=False, length=30), nullable=True),
    sa.Column('broker_notes', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('address_revealed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('doc_type', sa.String(length=100), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('allowed_user_ids', sa.JSON(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_thumbnail', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_properties',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seller_submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('seller_name', sa.String(length=255), nullable=False),
    sa.Column('seller_phone', sa.String(length=20), nullable=False),
    sa.Column('seller_email', sa.String(length=255), nullable=True),
    sa.Column('property_type', sa.Enum('flat', 'studio', 'villa', 'bungalow', 'duplex', 'penthouse', 'farmhouse', 'plot', 'commercial', 'office', 'shop', 'showroom', 'warehouse', 'coworking', name='propertytype', native_enum=False, length=30), nullable=False),
    sa.Column('listing_type', sa.Enum('sale', 'rent', 'lease', name='listingtype', native_enum=False, length=30), nullable=False),
    sa.Column('locality', sa.String(length=255), nullable=False),
    sa.Column('area_sqft', sa.Float(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('asking_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('submitted_photos', sa.JSON(), nullable=True),
    sa.Column('documents', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'reviewing', 'accepted', 'rejected', 'listed', name='submissionstatus', native_enum=False, length=30), nullable=True),
    sa.Column('broker_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('converted_property_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['converted_property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valuations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('property_id', sa.UUID(), nullable=True),
    sa.Column('submission_id', sa.UUID(), nullable=True),
    sa.Column('locality', sa.String(length=255), nullable=False),
    sa.Column('area_sqft', sa.Float(), nullable=False),
    sa.Column('property_type', sa.Enum('flat', 'studio', 'villa', 'bungalow', 'duplex', 'penthouse', 'farmhouse', 'plot', 'commercial', 'office', 'shop', 'showroom', 'warehouse', 'coworking', name='propertytype', native_enum=False, length=30), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('age_years', sa.Integer(), nullable=True),
    sa.Column('beach_distance_km', sa.Float(), nullable=True),
    sa.Column('region', sa.Enum('north_goa', 'south_goa', 'central_goa', name='goaregion', native_enum=False, length=30), nullable=False),
    sa.Column('estimated_low', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('estimated_mid', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('estimated_high', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['seller_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('valuations')
    op.drop_table('seller_submissions')
    op.drop_table('saved_properties')
    op.drop_table('property_images')
    op.drop_table('property_documents')
    op.drop_table('enquiries')
    op.drop_index(op.f('ix_properties_locality'), table_name='properties')
    
    op.drop_table('properties')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###